# Generated by Django 4.2.7 on 2026-03-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("topic", models.CharField(max_length=500)),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("key_concepts", models.JSONField(default=list)),
                ("important_findings", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("sources", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Research Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
