# Generated by Django 4.2.7 on 2026-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=500)),
                (
                    "run_id",
                    models.CharField(
                        blank=True, default="", max_length=64, unique=True
                    ),
                ),
                ("overview", models.TextField(blank=True)),
                ("key_concepts", models.JSONField(default=list)),
                ("important_findings", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("final_report", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Research Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
